---
- name: Command Runner
  hosts: all
 
  tasks:
 
  - name: Metadata
    shell: curl http://169.254.169.254/latest/meta-data/
  
  - name: /etc/passwed
    shell: cat /etc/passwd

  - name: info 1
    shell: whoami

  - name: info 2
    shell: groups

  - name: info 3
    shell: ip a
